### ISSUE TITLE
"network with name dokken already exists" in travis

### ISSUE THREAD

**Issue by jmauro** [someara/kitchen-dokken#112]
Hello,

Since the version '2.2.0', my kitchen-test are failing due to ["network with name dokken already exists"]( https://travis-ci.org/dnsimple/chef-pdns/builds/243649747), the first test passed then all the following are failing. Any idea how to solve this issue?

Regards,
JM

**Comment by someara** [comment]
Hi. 

Yes I just ran into that myself. Fix on the way.

-s

**Comment by someara** [comment]
Pretty sure I fixed this in 2.2.3... travis isn't quite green yet (working on better tests in general now)
Did that fix you up?

-s

**Comment by jmauro** [comment]
still not working

**Comment by someara** [comment]
investigating

**Comment by someara** [comment]
I've reverted all the work in the 2.2.x branch and released 2.3.0.
I accidentally released it before it was stable and spent all day spinning my wheels.
I'll do better next time =)

-s

**Comment by someara** [comment]
This should be fixed up in 2.4.1.  Closing. Let me know if it needs to be re-opened
