### ISSUE TITLE
Available kitchen version should be described in README.

### ISSUE THREAD

**Issue by odg0318** [someara/kitchen-dokken#124]
Hi.
Your driver doesn't work using `kitchen 1.10.0`.
Nowhere it is not described and so I was confused.
Upgrading kitchen to `1.16.0`, kitchen finally found your dokken driver.
Let me know from what version is available.

**Comment by someara** [comment]
1.16.0

**Comment by odg0318** [comment]
What do you think of writing the specification to README?

**Comment by someara** [comment]
send me a PR and I'll merge it
