### ISSUE TITLE
Clarify differences from kitchen-docker?

### ISSUE THREAD

**Issue by wjordan** [someara/kitchen-dokken#130]
Hello, I found this project through some Chef cookbook's integration-test setup and I'm curious about the motivation behind this project, and the differences in feature-set was from the official [`kitchen-docker`](https://github.com/test-kitchen/kitchen-docker) driver. I saw this brief blurb in the README:

> ### What about kitchen-docker?
> We already had a thing that drives Docker, why did you make this instead of modifying that?

> The current `kitchen-docker` driver ends up baking SSH, Chef, and the kitchen data
into the image. This does not. To make this work, I had to create a Driver, a Transport,
and a Provisioner that blur the traditional duties of each. The current Docker driver
can be used with Puppet, Ansible, CFEngine provisioners. This (for the time being) requires
Chef.

My questions:

- Is not "baking SSH, Chef, and the kitchen data into the image" a good thing, for specific reasons? I don't know what these reasons are from this brief description.
- If so, what practical advantages does not baking these things into the image offer over not baking them in, from the perspective of a user of this driver?
- If there are clear advantages, why is maintaining a separate driver necessary, rather than making a fork/pull request to integrate these improvements into the officially-maintained driver?
- What are some use-cases I would right now be better off using `kitchen-dokken` over `kitchen-docker`, and vice versa?

Thanks and good luck with the project!

**Comment by cheeseplus** [comment]
To be clear, kitchen-docker is in no way the official driver. Regardless of which one came first, WE (Chef) recommend kitchen-dokken and it's what we include in the ChefDK. That said, neither docker driver is owned or maintained by Chef Co.

The motivation is very much as written but I can add some more color:
- dokken pre-builds custom images to make things easier
- baking the chef-client into the images means you don't have to download and install Chef each run, a docker layer takes care of that
- not baking in means you can test the actual install of Chef, this is of dubious value to the average user but for advanced users it's more like non-docker drivers
- different drivers that do different things - each has advantages, if you are unsure use kitchen-dokken
- you're almost always better off using kitchen-dokken UNLESS you know that you should be using kitchen-docker (say with remote hosts or heavily customized docker options/images)

**Comment by wjordan** [comment]
Thanks so much for the extra details @cheeseplus, this helps me sort out the differences much better. I'll make a pass on a PR adding some of these details into this project's `README`, since I think it could help those less familiar with test-kitchen internals pick the best driver for their project.

Also, I think my confusion regarding [`kitchen-docker`](https://github.com/test-kitchen/kitchen-docker) being the official maintained-by-Chef driver came from that project's current GitHub owner being the [`test-kitchen`](https://github.com/test-kitchen) organization. If `kitchen-docker` is not in fact maintained by `test-kitchen` (which itself is "Maintained by Chef" according to its [public website](http://kitchen.ci/)), this should either be clarified in that project's `README`, or the project's GitHub ownership should be reassigned to the current maintainer. I'll make a note of this in that project's issue tracker as well.

**Comment by cheeseplus** [comment]
This can be closed cause I went and wrote a blog post :D https://blog.chef.io/2018/03/06/kitchen-docker-or-kitchen-dokken-using-test-kitchen-and-docker-for-fast-cookbook-testing/

**Comment by wjordan** [comment]
Thanks, this is extremely helpful! :tada :clap:
I've added a PR that adds a link to your blog post to the `README` so it remains accessible, and will close out this issue once it's merged.
