### ISSUE TITLE
Set Tag / Releases for several versions of this project

### ISSUE THREAD

**Issue by burtlo** [someara/kitchen-dokken#140]
This repository is missing a large number of tags/releases. Here are the suggested commits based on changes to the `lib/driver/dokken_version.rb` history. I don't know if that was the actual commit that was used when it came time to `gem push`.

Having these tag/releases help troubleshoot the state of the code at a particular point. Tonight I was working through an issue with Chef DK 2.4.17. This version uses kitchen-dokken 2.6.5. I gave someone the stacktrace and then started to track it into the code. But need to find the code at the state of the release.

Then I thought, well I should probably look at the other missing releases and suggest tags for those ones as well.

## Version 2.6.6 

Commit: a9538cc8ce3e6a304f0fd24f15fdc3653609e8d3

`git tag 2.6.6 a9538cc8ce3e6a304f0fd24f15fdc3653609e8d3`

## Version 2.6.5

Commit: 4b53140a0527fc4c3656f29f124232a15dd6f12f

`git tag 2.6.5 4b53140a0527fc4c3656f29f124232a15dd6f12f`

## Version 2.6.4

Commit: a0dd01593837851113707ad521043553cc127cc6

`git tag 2.6.4 a0dd01593837851113707ad521043553cc127cc6`

## Version 2.6.3

Commit: 98ec5b6732d530ade262583c8dd6fb79afcc1e54

`git tag 2.6.3 98ec5b6732d530ade262583c8dd6fb79afcc1e54`

## Version 2.6.2

Commit: c534d2c6b5c9ec06d6734f05e9db5a7038b447ae

`git tag 2.6.2 c534d2c6b5c9ec06d6734f05e9db5a7038b447ae`

## Version 2.6.1

Commit: 088ba4e43a499704297f3931332fcc089ba87a36

`git tag 2.6.1 088ba4e43a499704297f3931332fcc089ba87a36`

## Version 2.6.0 

Commit: 114fbb36631918ca225f1a1ae51ce8c35afc5f5c

`git tag 2.6.0 114fbb36631918ca225f1a1ae51ce8c35afc5f5c`

## Version 2.4.3 

Commit: 0a2d11fbed341e27c26c10e6e8b869d4300c4767

`git tag 2.4.3 0a2d11fbed341e27c26c10e6e8b869d4300c4767`

## Version 2.4.2

Commit: ed3657577de2eb5ce9b0a9e1fb1a7baa5b69ba57

`git tag 2.4.2 ed3657577de2eb5ce9b0a9e1fb1a7baa5b69ba57`

## Version 2.4.1

Commit: 529b2b5113e1adeb997c897330626123c15e72af

`git tag 2.4.1 529b2b5113e1adeb997c897330626123c15e72af`

**Comment by tas50** [comment]
Pushed. Thanks
