### ISSUE TITLE
Creating a docker network fails on Docker 1.7.1

### ISSUE THREAD

**Issue by burtlo** [someara/kitchen-dokken#141]
When Docker fails to create a network here:
https://github.com/someara/kitchen-dokken/blob/master/lib/kitchen/driver/dokken.rb#L346-L348

The error is a 404 message. That 404 message is re-displayed to the kitchen user.

I believe when this error is rescued it should contain additional information about what this gem was attempting to perform - create a network.

**Comment by tas50** [comment]
@burtlo I'm going to close this out at this point since 1.7.1 is WAY EOL. If this is still a problem on the supported Docker releases I can dig in.
