### ISSUE TITLE
Allow setting a hostname (and maybe just map values from .kitchen.yml)

### ISSUE THREAD

**Issue by rmoriz** [someara/kitchen-dokken#16]
Please allow providing a hostname value for the running instance.

Maybe a open/1:1 key/value mapping would also be cool for other options:

https://github.com/someara/kitchen-dokken/blob/8929f5c54abed378adcb0c0c31379334a7faf2a0/lib/kitchen/driver/dokken.rb#L182-L210

=> https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#create-a-container

**Comment by adampointer** [comment]
I really need this feature for this driver to truly replace kitchen docker at our company. I am happy to pick this up.

**Comment by someara** [comment]
closing. thanks!
