### ISSUE TITLE
Unable to change chef_environment

### ISSUE THREAD

**Issue by mike10010100** [someara/kitchen-dokken#163]
I'd like to be able to change my chef_environment for Dokken, but am currently unable to do so.

How it works using other test kitchen provisioners: https://docwhat.org/setting-environment-test-kitchen

**Comment by mike10010100** [comment]
@espoelstra Ah, perfect, it's able to see the environment now, but oddly I'm unable to get Dokken to recognize my example node:

```
provisioner:
  name: dokken
  always_update_cookbooks: true
  nodes_path: test/integration/nodes
  environments_path: test/environments
  client_rb:
    environment: kitchen```

Does the nodes_path section work with Dokken?

**Comment by espoelstra** [comment]
I believe it sets the node attributes automatically, I'm not sure if it supports passing them in as I didn't need to supply any node information in my testing.

**Comment by espoelstra** [comment]
See also https://github.com/someara/kitchen-dokken/issues/129
