### ISSUE TITLE
Failed to complete #create action: [undefined method `split' for nil:NilClass] on default-ubuntu-1604

### ISSUE THREAD

**Issue by kaihendry** [someara/kitchen-dokken#18]
Hi, I'm trying dokken since systemd is not support IIUC in docker-kitchen!? https://github.com/chef-cookbooks/cron/issues/79

<img src=http://s.natalian.org/2016-07-07/1467881680_2548x1380.png>

http://s.natalian.org/2016-07-07/dokken.log

**Comment by someara** [comment]
Make sure you're setting up your platform correctly...

...it needs to run privileged
https://github.com/someara/mysql/blob/aec3330a4e0680e661fef7fc9e950f7684ccc5a0/.kitchen.dokken.yml#L5

and you can start systemd like this:
https://github.com/someara/mysql/blob/aec3330a4e0680e661fef7fc9e950f7684ccc5a0/.kitchen.dokken.yml#L89

-s

**Comment by someara** [comment]
Closing this for now... please feel free to re-open if this is still an issue.
