### ISSUE TITLE
Allow pulling chef image from internal repository

### ISSUE THREAD

**Issue by ksexton** [someara/kitchen-dokken#24]
Please allow providing an image location for the chef artifact.  Environments with restricted access to the Internet will host images on an internal repo.  With the current implementation I am unable to point kitchen-dokken to an internal repo.

Note that data_image **does** allow pointing to internal repo:

`data_image: my.internal.repo/foo/kitchen-cache:latest`

It may make sense to kill out the chef_version variable and just reference something like `chef_image` with the version tag.

**Comment by someara** [comment]
Added a chef_image option in 4350872889006af66d4007838ef32d490fe7bd5c
released as 0.0.36
