### ISSUE TITLE
Need a chef/chef docker image for 12.14.89

### ISSUE THREAD

**Issue by chilicheech** [someara/kitchen-dokken#32]
Please build an image for chef-client 12.14.89 for use in dokken. Even better, please automate the builds so that a new image is built for every release of chef-client.

Cheers,

**Comment by rhass** [comment]
@someara We might be able to leverage mixlib-install to do this, or use https://nightli.es which @coderanger uses to build the poise gems regularly.

**Comment by someara** [comment]
Paging @tas50

**Comment by tas50** [comment]
On it!

**Comment by someara** [comment]
Pushing new images to `someara/chef`. 
Using them by default in dokken 1.0.1

-s

**Comment by someara** [comment]
done! closing
