### ISSUE TITLE
Allow dns

### ISSUE THREAD

**Issue by mengesb** [someara/kitchen-dokken#39]
Per kitchen-docker, there's a dns directive that's very helpful in vpn and other internal situations.  Could this be implemented?

https://github.com/test-kitchen/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb

**Comment by someara** [comment]
Sure! why the heck not.

**Comment by someara** [comment]
added in 33f1500a68f261d10f73d89f5ad3cb9516b26712, released as 1.0.5

**Comment by mengesb** [comment]
Thanks @someara !!! 👍
