### ISSUE TITLE
why-run in cookbooks

### ISSUE THREAD

**Issue by vadv** [someara/kitchen-dokken#48]
How I can test cookbook which must nothing to change with chef-client in whyrun mode?

**Comment by cheeseplus** [comment]
You would run chef-client with the `--why-run` flag. This isn't really an issue for the dokken driver and kitchen in general is about actual integration testing which is exactly what why-run/dry-run don't do for you.

There is even a great post about why you might not want to trust why-run/dry-run by the author of this driver: http://blog.afistfulofservers.net/post/2012/12/21/promises-lies-and-dryrun-mode/

**Comment by vadv** [comment]
> actual integration testing 
I want to test some heavy providers, that its don't change resources.
Why run mode is very useful and usable feature for system administrators. And we must be sure, what self written provider dont change resources.

**Comment by vadv** [comment]
like here: ![Ohh](http://image.prntscr.com/image/521d9aa90df14c0db1c2eef300380788.png)

**Comment by someara** [comment]
Out of scope for this plugin.

The best thing to do is converge twice and watch for green text, but that should be implemented up in test-kitchen, not in a a driver.

-s
