### ISSUE TITLE
issues with `someara/kitchen-cache:latest` image (89f8b7258d93) / DSA / SSH

### ISSUE THREAD

**Issue by rmoriz** [someara/kitchen-dokken#50]
=> https://github.com/someara/kitchen-dokken/blob/master/lib/kitchen/driver/dokken/helpers.rb

1.) sshd config

```
...
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
...
```
but host keys do not exist.

2.) since plain DSA keys are phased out in many distros, kitchen-dokken should probably switch to RSA (for max compatibility).

3.) 13 months old on docker hub but centos needs updates too :-)

**Comment by someara** [comment]
Fixed up in 2.0.0
