### ISSUE TITLE
Implement CI awareness ENV vars

### ISSUE THREAD

**Issue by someara** [someara/kitchen-dokken#54]
The first attempt didn't quite work....
https://github.com/someara/kitchen-dokken/pull/53/

I'd be nice if it worked on windows as well.

-s

**Comment by palfrey** [comment]
I added `'Env' => ['CI=1'],` to [start_runner_container](https://github.com/someara/kitchen-dokken/blob/4975160ba91b582adae634a9c42cc98f4f756063/lib/kitchen/driver/dokken.rb#L240)'s run_container which seems to work pretty well for me, certainly on OS X.

**Comment by hrak** [comment]
my current workaround is a check if `ENV['HOSTNAME'] == 'dokken'`
