### ISSUE TITLE
Kitchen Converge Says Chef Client is Running

### ISSUE THREAD

**Issue by kylegoch** [someara/kitchen-dokken#60]
Dokken Version: 2.0.1
Chef: 12.18.50 (set to latest in kitchen.yml)
Kitchen: 1.14.2

After running `kitchen converge`, if I run `kitchen converge` again it spits out the following:

```
14:35 $ kitchen converge
-----> Starting Kitchen (v1.14.2)
-----> Converging <default-ubuntu-1604>...
       Creating local sandbox in /Users/kyle/.dokken/sandbox/81440f96c8-default-ubuntu-1604
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.2.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
Starting Chef Client, version 12.18.50
[2017-01-24T19:51:49+00:00] WARN: Port 8889 not available
[2017-01-24T19:51:49+00:00] WARN: Chef client 10133 is running, will wait for it to finish and then run.
[2017-01-24T19:52:51+00:00] WARN: Port 8889 not available
[2017-01-24T19:52:51+00:00] WARN: Port 8890 not available
[2017-01-24T19:52:51+00:00] WARN: Chef client 10133 is running, will wait for it to finish and then run.
[2017-01-24T19:53:55+00:00] WARN: Chef client 10655 is running, will wait for it to finish and then run.
[2017-01-24T19:54:59+00:00] WARN: Port 8889 not available
[2017-01-24T19:54:59+00:00] WARN: Port 8890 not available
[2017-01-24T19:54:59+00:00] WARN: Port 8891 not available
[2017-01-24T19:54:59+00:00] WARN: Chef client 10655 is running, will wait for it to finish and then run.
```

I thought in the past, that re-running `kitchen converge` would reurun the client similar to chef server and update the appropriate resources. But now it just gets hung as shown above.

Meaning if I converge, find an error in my code, and fix it. I must do `kitchen destroy` then `kitchen converge` to confirm the error is fixed.

**Comment by someara** [comment]
I just spot checked this and wasn't able to reproduce it...
Do you happen to have the chef-client cookbook in your run_list or anything like that?

-s

**Comment by kylegoch** [comment]
I thought that was the issue, as I get that behavior on a cookbook i have that does have `chef-client` in its run list.

But on a different cookbook that does not have `chef-client` in it's run list, i get the same action.
Here are the cookbooks that Kitchen syncs for the cookbook, and there is no `chef-client`.
```
Synchronizing Cookbooks:
  - chef_base (0.1.10)
  - ntp (3.3.1)
  - motd (0.6.4)
  - openssh (2.1.1)
  - cron (3.0.0)
  - poise-python (1.5.1)
  - aws (4.2.0)
  - filebeat (0.4.6)
  - datadog (2.7.0)
  - chef_handler (1.4.0)
  - iptables (3.1.0)
  - poise (2.7.1)
  - poise-languages (2.0.4)
  - ohai (4.2.3)
  - windows (2.1.1)
  - apt (5.0.1)
  - yum (4.1.0)
  - yum-plugin-versionlock (0.1.2)
  - runit (3.0.3)
  - compat_resource (12.16.3)
  - poise-archive (1.3.0)
  - packagecloud (0.2.5)
  - yum-epel (2.1.1)
```

But doing `kitchen converge` waiting till it finished and running `kitchen converge` yields the same error above. Even though this cookbook does not have `chef-client` in its run list.

**Comment by someara** [comment]
What happens if you nuke all the stuff in your docker engine and "start over"?

docker rm -f `docker ps -aq` ; docker rmi `docker images -q` ; rm -rf .kitchen ; kitchen converge ; kitchen converge

**Comment by kylegoch** [comment]
I ran the above, and still getting the same error on the second converge. Ill go try a completely differnet cookbook, that isnt either of these two so far and report back.

**Comment by someara** [comment]
Please do. I'm really curious about what's going on here.
-s

**Comment by someara** [comment]
I finally ran into this myself.... it seems to happen with a large number (+~2 - 5) of suites.
Especially when using concurrency

**Comment by kylegoch** [comment]
I finally got around to trying another cookbook as well. The third cookbook was fine and worked as expected.

Also, my findings seem to support that as well.
- First Cookbook: caused by chef-client cookbook
- Second Cookbook: no chef-client, but has 3 suites
- Third Cookbook: no chef-client, one suite

**Comment by someara** [comment]
Are you still seeing this? A few revisions ago I realized I wasn't cleaning up the sandbox on destroy...
Now that I'm thinking about it, I bet chef-client dropped a pid file off in there.

-s

**Comment by kylegoch** [comment]
I havent been in test kitchen this week, but from above it, it does work properly in another cookbook. So its not a test kitchen issue. It might just be something in my own cookbook (the second one that is, that didnt work but didnt have chef-client).

Thanks for looking into this and getting it squared away!

**Comment by kylegoch** [comment]
@someara Well, spoke to soon. Back in Test Kitchen today, brand new cookbook, same issue.

Ran a converge to test my first run at the cookbook. It failed. Fixed the change, then got the chef-client error again.

**Comment by someara** [comment]
Are you using a remote docker host? or the laptop local virt

**Comment by kylegoch** [comment]
Local on my laptop

**Comment by someara** [comment]
I've added some docker-in-docker goodness to the defaut test suite.

https://github.com/someara/kitchen-dokken/blob/d6d1d0026b9da63cc54b8dd87e427fd409562052/test/cookbooks/dokken_test/recipes/default.rb

Next time this happens, let's try and duplicate the conditions in there.

-s

**Comment by kylegoch** [comment]
Still happening in Chef 12.19, still random though.

Did this too, just in case:
`docker rm -f `docker ps -aq` ; docker rmi `docker images -q` ; rm -rf .kitchen`

**Comment by stormerider** [comment]
I've been having this as well, if I destroy first I'm golden, if I try to reconverge, it's problematic. But we do call chef-client::service in our base cookbook. (I can try to disable that under TK, but I thought it already was for local mode.)

**Comment by kylegoch** [comment]
@stormerider I have been disabling chef-client recipes (then have to remember to go back and re-enable them) and still get this issue.

Is there a better way to prevent chef-client recipes from running other than commenting them out?

**Comment by kylegoch** [comment]
Upgrade to `kitchen-dokken` 2.1.2 did not solve the issue.
Test kitchen version 1.15.0 as well.

**Comment by kylegoch** [comment]
Sometimes, the rogue chef run will clear itself after blocking:
```
[2017-04-26T17:55:19+00:00] WARN: Chef client 70 is running, will wait for it to finish and then run.
[2017-04-26T17:56:21+00:00] WARN: Port 8889 not available
[2017-04-26T17:56:21+00:00] WARN: Port 8890 not available
[2017-04-26T17:56:21+00:00] WARN: Chef client 70 is running, will wait for it to finish and then run.
```
Then the chef run will occur

**Comment by delta440** [comment]
For me this issue seems to be related to long running resources. 
`
execute 'sleep 100' do
  action :run
end
`
Causes the issue, but
`
execute 'sleep 10' do
  action :run
end
` 
Does not
