### ISSUE TITLE
What is in someara/kitchen-cache?

### ISSUE THREAD

**Issue by jason-riddle** [someara/kitchen-dokken#65]
Is there a Dockerfile available for this image?

**Comment by someara** [comment]
Hi.

someara/kitchen-cache is deprecated as of 2.0.0.

For local docker hosts, dokken now bind mounts the data, making it unnecessary.
For remote docker hosts, it is now generated on the fly.

https://github.com/someara/kitchen-dokken/blob/931083b4449b98f15a8d91c84bf68fc31306e9dd/lib/kitchen/helpers.rb#L40-L59

-s

**Comment by jason-riddle** [comment]
Ok, thanks for mentioning that. I noticed that chef-dk has pinned the version at 1.1.0 (https://github.com/chef/chef-dk/blob/6388d78/Gemfile#L64). I'll create an issue over there to update that gem. Closing.

**Comment by jason-riddle** [comment]
https://github.com/chef/chef-dk/issues/1166

**Comment by someara** [comment]
They track dokken pretty closely. They pinned because they ran into https://github.com/someara/kitchen-dokken/issues/62

**Comment by jason-riddle** [comment]
Ah ok.

**Comment by jason-riddle** [comment]
Bumped in https://github.com/chef/chef-dk/commit/2da7387e907d7218f271f879eb79becb810e2075. Thanks.
