### ISSUE TITLE
kitchen-dokken displaying login page for guest os on terminal during converge. 

### ISSUE THREAD

**Issue by rshade** [someara/kitchen-dokken#73]
I am using ubuntu 14.04.5 LTS, chef dk 1.2.22, docker 1.13.1, when I run kitchen converge against this https://github.com/sous-chefs/swap/blob/add-inspec-to-dokken/.kitchen.dokken.yml, I get a local login prompt, for the guest os and it does not complete or completes in the background. I can not tell as it controls the tty

**Comment by someara** [comment]
Upgrade to the latest kitchen-dokken with "gem install kitchen-dokken"
