### ISSUE TITLE
Failed to complete #verify action: [Permission denied @ dir_s_mkdir - /home/travis/.dokken/verifier_sandbox/5caa8e4ee9-default-centos-6/suites] on default-centos-6]

### ISSUE THREAD

**Issue by dhoer** [someara/kitchen-dokken#74]
I can't figure out why I'm getting this:  
https://travis-ci.org/dhoer/chef-nexus3/jobs/206878136#L778

On all flavors of linux:
https://travis-ci.org/dhoer/chef-nexus3/builds/206878135

I don't think it is dokken because another project builds with the same gems:
https://travis-ci.org/dhoer/chef-selenium

Any hints on what might be going on here would be greatly appreciated.

**Comment by dhoer** [comment]
I was doing a chown on /opt folder and causing this issue.

**Comment by someara** [comment]
Thanks for letting me know!
