### ISSUE TITLE
Documentation seems outdated

### ISSUE THREAD

**Issue by wesm-outreach** [someara/kitchen-dokken#76]
Specifically around the tests. The `README.md` refers to `hello_dokken` several times but I don't see that recipe anywhere in the repo. I'm trying to piece together how tests should actually look.

**Comment by someara** [comment]
https://github.com/someara/hello_dokken

**Comment by wesm-outreach** [comment]
Oh, thanks! Readme should be updated with a link maybe?

**Comment by someara** [comment]
README PR's are my favorite kind of PR ;)

**Comment by wesm-outreach** [comment]
haha, I'll send a PR after I get my shit together. I'm a bit new to chef/test-kitchen (familiar with docker though).

**Comment by someara** [comment]
closing this here for now.
