### ISSUE TITLE
Documentation for using Inspec

### ISSUE THREAD

**Issue by wesm-outreach** [someara/kitchen-dokken#77]
I wrote a simple inspec test, but it's running on the host, not the container. Not sure what I'm doing wrong. Any help would be appreciated. Serverspec however is running on the container.

**Comment by someara** [comment]
Inspec does indeed run on the host.
That's by (inspec) design.

It connects to the container through the transport (docker exec).

You'll have problems doing things like checking for listening ports or whatever if you're mounting the local docker socket.

-s
