### ISSUE TITLE
Use train as transport

### ISSUE THREAD

**Issue by chris-rock** [someara/kitchen-dokken#8]
May it make sense to reuse [train](https://github.com/chef/train) as a transport?

**Comment by someara** [comment]
Yes please!

How can I use train to transfer a directory of files?

Right now the data container uses ssh+rsync to move from the workstation to
the volume container

https://github.com/someara/kitchen-dokken/blob/c2e374c94eb64bd8eee71f15d2a1304037fc4c27/lib/kitchen/transport/dokken.rb#L113-L114

I'm digging around in the inspec test directory, but I'm not seeing an
example jump out at me.

Any advice?

-s

**Comment by chris-rock** [comment]
Oh, yeah I missed that. Train does not support file upload yet, but it should. Lets see how fast we are with implementing that feature: https://github.com/chef/train/issues/59
