### ISSUE TITLE
Chef Gems with Extensions

### ISSUE THREAD

**Issue by bdwyertech** [someara/kitchen-dokken#80]
Just leaving this here as a note, because a `chef_gem` resource with platform extensions can cause problems.

E.g. the `mysql2` gem in the `database` cookbook which uses Mysql libraries during compilation.

Basically the `chef_gem` gets written back to the Chef container with lib references from the first platform. Typically these resolve symlinks so a reference to lets say `libmysqlclient.so` may resolve to a version specific `libmysqlclient.so.18`. In the case of Centos 7 vs Ubuntu 16.04 these clash due to library version differences.

Not sure what could handle this, maybe a Boolean that let's you disable the chef container for corner cases like this, so you can install chef with an intermediate command in the image rather than using the `chef/chef` container. Realistically this could be resolved in the cookbook by ensuring ruby is installed and using a regular `gem` resource rather than the `chef_gem` resource, but it does bring about a dilemma.

**Comment by someara** [comment]
I'm not really sure that there's anything that can be done about this.

chef_gem installation has always been a mine field. 
Here is Yet Another Example why.

The best thing to do would be to include these libs in Core, but The Maintainers are likely unwilling.
Closing here for lack of anything I can do about it.
-s
