### ISSUE TITLE
Run custom base image

### ISSUE THREAD

**Issue by tanner-bruce** [someara/kitchen-dokken#81]
I'm interested in using my own custom base image with dokken. We maintain a small amount of base images that have things like Java or Ruby, etc, pre-installed on them, along with a few other things, and would like to take advantage of this, even if I were to have to extend, so to speak, our base images into a custom version for dokken that would be ok.

Is there documentation anywhere on what would need to be done to do this?

**Comment by someara** [comment]
simply specify your image in your driver config

so, instead of "debian:7", use "myimage:whatever"
https://github.com/chef-cookbooks/docker/blob/master/.kitchen.dokken.yml#L23

-s
