### ISSUE TITLE
Rake aborted when tests fail

### ISSUE THREAD

**Issue by fernandoaleman** [someara/kitchen-dokken#82]
When a test fails, I get a `rake aborted!` error on the command line. Is this what's supposed to happen?

![screen shot 2017-03-15 at 1 09 03 pm](https://cloud.githubusercontent.com/assets/523634/23966321/e898c214-0988-11e7-9983-f817558bffc3.png)

**Comment by someara** [comment]
I'm not sure. I don't run my tests with Rake.
Check your Rakefile.

-s
