### ISSUE TITLE
Readme: USAGE unclear

### ISSUE THREAD

**Issue by rmoriz** [someara/kitchen-dokken#86]
Hi,

I think the readme is confusing regarding the USAGE. IMHO in the usual scenario a `.kitchen.yml` already exists and is configured to use vagrant as the default driver.

To use dokken, the user can just specify an "overlay" configuration, as you point out:

```
export KITCHEN_YAML=.kitchen.yml
export KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
```

However the subsequent `cat` of `.kitchen.yml` shows probably what meant to be `.kitchen.dokken.yml` and also specifies its own runlist/suites - it does not show the "inheritance/overlay" functionality.

What do you think?

**Comment by someara** [comment]
You're probably right. PRs accepted.
