### ISSUE TITLE
Need better error message for failing to build the work image

### ISSUE THREAD

**Issue by shortdudey123** [someara/kitchen-dokken#95]
**Problem**

If the call to [`::Docker::Image.build`](https://github.com/someara/kitchen-dokken/blob/2ef7992064516a4983cc56f716adccc98ce1c9a3/lib/kitchen/driver/dokken.rb#L130) to build the `work_image` fails, the error message of `work_image build failed` is not very descriptive as to what happened.

Adding this to the rescue section in addition to what is there would make it more descriptive (code is not pretty and can be improved).  Let me know what you think and I can put in a PR with prettier code.
```
rescue  Docker::Error::UnexpectedResponseError => e
  raise "work_image build failed: #{JSON.parse(e.to_s.split("\r\n").last)['error']}"
```

**Current output:**
```
>>>>>>     Failed to complete #create action: [work_image build failed] on default-freebsd-10
```
```
D      Message: Failed to complete #create action: [work_image build failed]
```

**Suggested solution output:**
```
>>>>>>     Failed to complete #create action: [work_image build failed: The command '/bin/sh -c /bin/sh -c "echo Built with Test Kitchen"' returned a non-zero code: 139] on default-freebsd-10
```
```
D      Message: Failed to complete #create action: [work_image build failed: The command '/bin/sh -c /bin/sh -c "echo Built with Test Kitchen"' returned a non-zero code: 139]
```

**Comment by someara** [comment]
In my experience this error is usually a result of one of two things

1) something is wrong with the the `intermediate_instructions` (forgot to apt-get update)
2) some transient failure happening (apt/yum repo unresponsive)

A more descriptive message would suggest one of both of those.

Thanks!

-s

**Comment by shortdudey123** [comment]
So in my case it was actually neither of the ones you mentioned.  In my case it was a SEGFAULT from docker.
